### ISSUE TITLE
Bad data in analysis-request JSON issue with simple MetaCoin contract

### ISSUE THREAD

**Issue by sjukeshov** [cleanunicorn/mythos#26] opened 2019-03-28 09:26 UTC
```
mythos analyze contracts/MetaCoin.sol MetaCoin
Reading contract contracts/MetaCoin.sol... done
Downloading Solidity version v0.5.6+commit.b259423e
Compiling contract contracts/MetaCoin.sol... done
Analyzing contract MetaCoin... !
 ›   Error: Bad data in analysis-request JSON:
 ›   In contract MetaCoin:
 ›   * field "bytecode" with value 
 ›   "608060405234801561001057600080fd5b506127106000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506103cd80610065600039600
 ›   0f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80637bd703e81461004657806390b98a111461009e578063f8b2cb4f14610104575b600080fd5b6100886004803603602081101561005c57600080fd5b8101908
 ›   0803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061015c565b6040518082815260200191505060405180910390f35b6100ea600480360360408110156100b457600080fd5b81019080803573fffffffffffffff
 ›   fffffffffffffffffffffffff16906020019092919080359060200190929190505050610200565b604051808215151515815260200191505060405180910390f35b6101466004803603602081101561011a57600080fd5b81019080803573fffffffff
 ›   fffffffffffffffffffffffffffffff169060200190929190505050610359565b6040518082815260200191505060405180910390f35b600073__$790e28c6efc44c91dd5ccaef91022121eb$__6396e4ee3d61018184610359565b60026040518363f
 ›   fffffff1660e01b8152600401808381526020018281526020019250505060206040518083038186803b1580156101be57600080fd5b505af41580156101d2573d6000803e3d6000fd5b505050506040513d60208110156101e857600080fd5b8101908
 ›   0805190602001909291905050509050919050565b6000816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015610251576000905061035
 ›   3565b816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550816000808573fffffffffffffffffffffffffffff
 ›   fffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508273ffffffffffffffffffffffffffffffffffffffff163373fffffffffffffffffffffffffffffffffffff
 ›   fff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a3600190505b92915050565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673fff
 ›   fffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905091905056fea165627a7a7230582087bea34fb0204ed8aedb0e949e6f827727539a746de69e8c7a838bc8d7db92180029" fails to match the required 
 ›   pattern: /^(0x)?([0-9a-fA-F]{2})+$/
 ›   * field "deployedBytecode" with value 
 ›   "608060405234801561001057600080fd5b50600436106100415760003560e01c80637bd703e81461004657806390b98a111461009e578063f8b2cb4f14610104575b600080fd5b6100886004803603602081101561005c57600080fd5b81019080803
 ›   573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061015c565b6040518082815260200191505060405180910390f35b6100ea600480360360408110156100b457600080fd5b81019080803573fffffffffffffffffff
 ›   fffffffffffffffffffff16906020019092919080359060200190929190505050610200565b604051808215151515815260200191505060405180910390f35b6101466004803603602081101561011a57600080fd5b81019080803573fffffffffffff
 ›   fffffffffffffffffffffffffff169060200190929190505050610359565b6040518082815260200191505060405180910390f35b600073__$790e28c6efc44c91dd5ccaef91022121eb$__6396e4ee3d61018184610359565b60026040518363fffff
 ›   fff1660e01b8152600401808381526020018281526020019250505060206040518083038186803b1580156101be57600080fd5b505af41580156101d2573d6000803e3d6000fd5b505050506040513d60208110156101e857600080fd5b81019080805
 ›   190602001909291905050509050919050565b6000816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410156102515760009050610353565
 ›   b816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550816000808573fffffffffffffffffffffffffffffffff
 ›   fffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1
 ›   67fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a3600190505b92915050565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673fffffff
 ›   fffffffffffffffffffffffffffffffff16815260200190815260200160002054905091905056fea165627a7a7230582087bea34fb0204ed8aedb0e949e6f827727539a746de69e8c7a838bc8d7db92180029" fails to match the required 
 ›   pattern: /^(0x)?([0-9a-fA-F]{2})+$/
.../MetaCoin$ mythos -v
@cleanunicorn/mythos/0.5.0 linux-x64 node-v11.6.0
```

**Comment by cleanunicorn** [comment] 2019-03-28 10:27
This looks weird. 

Can you please format the output?

**Comment by cleanunicorn** [comment] 2019-03-28 15:10
The sent data seems to match the regex rule. I assume it might be a problem on the MythX side. 

Can you provide the Solidity source code so I can check?
And if possible can you check one more time?

I hope this is not related to #27

**Comment by sjukeshov** [comment] 2019-03-28 15:23
[contracts.zip](https://github.com/cleanunicorn/mythos/files/3018721/contracts.zip)
try out with these please

**Comment by eswarasai** [comment] 2019-03-28 20:52
This issue has been fixed in `sabre` if I'm not wrong. @b-mueller can confirm though.

I'll try to quickly create a PR and check with the above shared contracts to see if the issue is fixed.

Ref: https://github.com/b-mueller/sabre/commit/5934c5b26746865ddf4256135ce59a504876fc18#diff-f94a6673e2badf4445e6cc4f366ddc9cR79

**Closed** 2019-03-28 21:05 UTC
